export default {
    MC_GET_GRADE_WEIGHT: 'MC_GET_GRADE_WEIGHT',
    MC_GET_GRADE_WEIGHT_SUCCESS: 'MC_GET_GRADE_WEIGHT_SUCCESS',
    MC_GET_GRADE_WEIGHT_FAILED: 'MC_GET_GRADE_WEIGHT_FAILED',
    MC_UPDATE_GRADE_WEIGHT: 'MC_UPDATE_GRADE_WEIGHT',
    MC_UPDATE_GRADE_WEIGHT_SUCCESS: 'MC_GET_GRADE_WEIGHT_SUCCESS',
    MC_UPDATE_GRADE_WEIGHT_FAILED: 'MC_GET_GRADE_WEIGHT_FAILED',
    GRADE_WEIGHTING_SET_STATE: 'GRADE_WEIGHTING_SET_STATE',
};
