export const actions = {
  UPDATE_MY_PROFILE: 'UPDATE_MY_PROFILE',
  UPDATE_MY_PROFILE_SUCCESS: 'UPDATE_MY_PROFILE_SUCCESS',
  UPDATE_MY_PROFILE_FAILED: 'UPDATE_MY_PROFILE_FAILED',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

  UPDATE_BEDTIME_PREFERENCE: 'UPDATE_BEDTIME_PREFERENCE',
  UPDATE_BEDTIME_PREFERENCE_SUCCESS: 'UPDATE_BEDTIME_PREFERENCE_SUCCESS',
  UPDATE_BEDTIME_PREFERENCE_FAILED: 'UPDATE_BEDTIME_PREFERENCE_FAILED',
  
  RESET_MY_PROFILE_REDUCER: 'RESET_MY_PROFILE_REDUCER',
  MY_PROFILE_SET_STATE: 'MY_PROFILE_SET_STATE',
};

export const END_POINT = {
  update_my_profile: {
      method: 'PUT',
      url: `${process.env.REACT_APP_API_URL}/organization/profile`
  },
  change_password: {
    method: 'PUT',
    url: `${process.env.REACT_APP_API_URL}/organization/change-password`
}
};